name: Weekly Test

on:
  schedule:
    - cron: "0 7 * * 1" # Every Monday @ 7

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - name: Test
        env:
          USERNAME: ${{ secrets.USERNAME }}
          SECRET: ${{ secrets.SECRET }}
          SKIP_WIP: true
        run: go test -v ./...